version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: git config --global user.email "wisarutgolf11@gmail.com"
            - run: git config --global user.name "GGolfz"
            - run: npm run deploy
            
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy